apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# managedcluster is clusterwide need clusterrolebinding
  - ztp-monitor-sa.yaml
  - ztp-monitor-rbac.yaml
  - ztp-monitor-clusterrolebinding.yaml
  - ztp-monitor-deployment.yaml
