apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-monitor
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: mc-monitor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: mc-monitor
    spec:
      containers:
      - args:
        - |
          set -o errexit
          set -o nounset
          set -o pipefail
          #unset KUBECONFIG
          cat <<SCRIPT > /tmp/mc-monitor
          #!/bin/bash
          echo $@

          function monitor_mc_labels {
            
            until [[ \$(oc get managedcluster --selector='ztp-done=') || \$(oc get managedcluster --selector='ztp-running=')  ]]; do
              echo "Waiting for cluster install to finish or DU profile to be applied"
              sleep 1;
            done
          }

          function log_message_update_labels {
            managedcluster_name=\$1

            label="false"

            if [[ \$(oc get managedcluster --selector='ztp-done=') ]]; then
              label="ztp-done"
            fi

            if [[ \$(oc get managedcluster --selector='ztp-running=') ]]; then
              label="ztp-running"
            fi

            case \$label in
            
            ztp-running)
              echo "Adding true to ztp-running label on \$managedcluster_name - This cluster is finished installing"
              oc label managedcluster --overwrite \$managedcluster_name ztp-running=true
              ;; 
            ztp-done)
              echo "Adding true to ztp-running label on \$managedcluster_name - The DU profile has been applied"
              oc label managedcluster --overwrite \$managedcluster_name ztp-done=true 
              ;;

            esac
          }

          case \$KUBE_ACTION in
            Updated) monitor_mc_labels
                   log_message_update_labels \$*
                   ;;
          esac
          SCRIPT
          chmod u+x /tmp/mc-monitor

          exec oc observe managedcluster --type-env-var=KUBE_ACTION --maximum-errors=1 --resync-period=10m --template='{.metadata.name}' -- /tmp/mc-monitor
        command:
        - /bin/bash
        - -xc
        #- "sleep 9000"
        image: jumphost.inbound.vz.bos2.lab:5000/openshift4/ose-cli@sha256:728b0198d84b0730f17b07103d00391c18b8c4f2c9c75d64aa6b7aba83185d59
        imagePullPolicy: IfNotPresent
        name: mc-monitor
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: ztp-monitor-mc 
      serviceAccountName: ztp-monitor-mc
      terminationGracePeriodSeconds: 30

