apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-ztp-monitor-mc 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-ztp-monitor-mc 
subjects:
- kind: ServiceAccount
  name: ztp-monitor-mc 
  namespace: open-cluster-management
